stevie2codes/Animade

client/public/index.html, client/src/App.js, client/src/components/animationContainer.js, client/src/components/nav/nav.js, client/src/index.scss, client/src/pages/animations.js, client/src/pages/home.js, client/src/sass/animationContainer.scss, client/src/sass/home.scss, client/src/sass/navbar.scss
spruced up the home page with animations and color fixes , Also started work on the main animations page
=> HomeAnimate and start animation page

client/src/components/animationContainer.js, client/src/components/signUp.js, client/src/sass/animationContainer.scss
sign in inputs to accomadate backend
=> fixed sign up 

client/src/components/animationContainer.js, client/src/components/dropdown.js, client/src/pages/animations.js, client/src/sass/animationContainer.scss, package-lock.json, package.json
Installed list component and setup logo to be animated. Added small list of general animation names.
=> Animation page revamp

models/User.js, package-lock.json, package.json, routes/userRoutes.js
Have passwords hashing correctly, and also have the signin route comparing the entered username/password to our DB, and seeing if they are correct, or incorrect
=> Authentication

client/src/pages/animations.js, client/src/sass/animationContainer.scss
=> animation redo

client/src/components/animationContainer.js, client/src/pages/animations.js, client/src/sass/animationContainer.scss, client/src/sass/home.scss, client/src/sass/pureAnimation.scss, client/src/services/animationService.js
animations updated to show 4 and updated object array with data.
=> Updated animations

client/src/pages/animations.js, client/src/sass/animationContainer.scss, client/src/services/animationService.js
ReWork on displaying animations to display classes
=> logging keyframes

client/src/pages/animations.js, client/src/sass/animationContainer.scss, client/src/sass/modal.scss, package-lock.json, package.json
Added NPM package to help facilitate copy to clipboard functionality.
=> Modal Style / Copy to clipboard

client/src/components/signIn.js, client/src/components/signUp.js, client/src/pages/animations.js, client/src/sass/animationContainer.scss, client/src/sass/modal.scss, client/src/services/animationService.js
more animations added and styled a little differently
=> Added 6 more animations

client/src/App.js, client/src/components/pagination.js, client/src/pages/animations.js, client/src/pages/playground.js, client/src/sass/playground.scss, client/src/services/paginate.js, package.json
Pagination styling will still be tweaked and added a playground route to move to the next phase of things
=> added pagination and a playground page

client/src/components/pagination.js, client/src/pages/playground.js, client/src/sass/modal.scss, client/src/sass/pagination.scss, client/src/sass/playground.scss, package-lock.json, package.json
Got the playground functioning, Having issues with the JS side but might just take that out. 
Used and NPM package called code mirror. Need to fix issues with the javascript side of the editor.
=> Styled Pagination and added a Functional Playground

client/src/pages/playground.js, client/src/sass/home.scss, client/src/sass/playground.scss
Added theme and other tweaks ie number gutters to the code playground
=> Playground IDE tweaks

client/src/App.js, client/src/components/signUp.js, client/src/pages/profile.js
=> profile page

client/src/components/three.js, client/src/pages/contact.js, client/src/pages/home.js, client/src/pages/playground.js, client/src/sass/home.scss, package-lock.json, package.json
added three js component for later use
=> three.js animation componet

client/src/pages/home.js, client/src/pages/playground.js, client/src/sass/home.scss, client/src/sass/playground.scss
SignIn button  on homepage and Input on playground for user to save playmation
=> SignIn button and Input on playground

client/src/components/repo.js, client/src/components/three2.js, client/src/index.scss, client/src/pages/contact.js, client/src/pages/home.js, client/src/sass/contact.scss
added three.js components, cards with links  and made a new repo component for home and contact page.
=> Contact page full setup

client/src/App.js, client/src/index.scss, client/src/pages/home.js, client/src/sass/animationContainer.scss, client/src/sass/filterList.scss, client/src/sass/home.scss, client/src/sass/modal.scss, client/src/sass/pagination.scss, client/src/services/animationService.js
added entrance animations and fixed up some ui elements.
=> More animations added

client/src/components/homeCube.js, client/src/components/nav/nav.js, client/src/pages/playground.js, client/src/pages/profile.js, client/src/sass/playground.scss, client/src/sass/profile.scss
added username to playground  and restyled welcome text in profile page.
=> Stylings to profile and playground

client/src/components/nav/nav.js, client/src/pages/contact.js, client/src/pages/playground.js, client/src/pages/profile.js, client/src/sass/animationContainer.scss, client/src/sass/contact.scss, client/src/sass/navbar.scss
Added info to author cards. And added a better ternary to the playground user name
=> Contact page info

client/src/pages/contact.js, client/src/pages/profile.js, client/src/sass/profile.scss
Linked up playmation from profile to playground
=> Linked up playmation 

client/src/pages/playground.js, client/src/utils/API.js, routes/api/savedPlaygroundCode.js
When clicked on from profile page, the user is sent to the playground page with whichever code block they clicked, and they can update their existing code, and it will update in DB, instead of creating another new entry.
=> correctly updating saved playground code instead of creating another new

client/src/components/isolatedSvg.js, client/src/pages/profile.js, client/src/sass/contact.scss, client/src/sass/playground.scss, client/src/sass/profile.scss
styled svgs for data output on profile page
=> svg stylings for profile page

client/src/components/isolatedSvg.js, client/src/pages/animations.js, client/src/pages/profile.js, client/src/sass/animationContainer.scss, client/src/sass/filterList.scss, client/src/sass/modal.scss, client/src/sass/profile.scss
many new styling fixes and touch ups
=> many new styling fixes and touch ups

client/src/pages/playground.js, client/src/sass/playground.scss
trying to fix playground scroll problem
=> scroll bar fix?
